"""Generate the Deaiify Vale style from upstream AI-slop data sources.

Sources (fetched from main/master at run time, retrieval noted in headers):
- Kobak et al. excess_words.csv (berenslab/llm-excess-vocab, MIT)
- slop-forensics curated lists (sam-paech/slop-forensics, MIT)
- Nous ANTI-SLOP.md tables (NousResearch/autonovel, NO LICENSE) — OPT-IN only
  (`--include-nous`); written to gitignored Nous*.yml for local private use,
  never committed or redistributed by this repo.

Run: uv run python tools/build_rulepacks.py [--include-nous]
"""

import csv
import datetime
import io
import json
import re
import urllib.request
from pathlib import Path

import yaml

OUT = Path(__file__).resolve().parent.parent / "rulepacks" / "en" / "Deaiify"

KOBAK_URL = "https://raw.githubusercontent.com/berenslab/llm-excess-vocab/main/results/excess_words.csv"
SLOP_WORDS_URL = "https://raw.githubusercontent.com/sam-paech/slop-forensics/main/data/slop_list.json"
SLOP_TRIGRAMS_URL = "https://raw.githubusercontent.com/sam-paech/slop-forensics/main/data/slop_list_trigrams.json"
NOUS_URL = "https://raw.githubusercontent.com/NousResearch/autonovel/master/ANTI-SLOP.md"

# Kobak rows to keep: open-class words only; closed-class hits are register
# noise ("across", "within") rather than actionable tells.
KOBAK_POS = {"verb", "adjective", "adverb", "noun"}


def fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=60) as r:
        return r.read().decode("utf-8")


def write_rule(name: str, rule: dict, source: str, license_note: str):
    header = (f"# Generated by tools/build_rulepacks.py on {datetime.date.today()} — do not edit.\n"
              f"# Source: {source}\n# License: {license_note}\n")
    body = yaml.safe_dump(rule, sort_keys=False, allow_unicode=True, width=100)
    (OUT / f"{name}.yml").write_text(header + body, encoding="utf-8")
    n = len(rule.get("tokens", rule.get("swap", [])))
    print(f"  {name}.yml: {n} entries")


def kobak_rules():
    rows = list(csv.DictReader(io.StringIO(fetch(KOBAK_URL))))
    words = sorted({r["word"] for r in rows
                    if r["type"] == "style" and r["part_of_speech"] in KOBAK_POS})
    write_rule("KobakExcessWords", {
        "extends": "existence",
        "message": "'%s' is excess vocabulary in LLM output (Kobak et al. 2025).",
        "level": "suggestion",
        "ignorecase": True,
        "tokens": words,
    }, KOBAK_URL, "MIT (berenslab/llm-excess-vocab)")


def slop_forensics_rules():
    words = sorted({w[0] for w in json.loads(fetch(SLOP_WORDS_URL))})
    write_rule("SlopWords", {
        "extends": "existence",
        "message": "'%s' is on the slop-forensics overused word list.",
        "level": "suggestion",
        "ignorecase": True,
        "tokens": words,
    }, SLOP_WORDS_URL, "MIT (sam-paech/slop-forensics)")

    # Trigrams are stopword-stripped upstream ("plays crucial role" matched
    # "plays a crucial role"), so allow up to two filler words per gap.
    # Bigrams are skipped: after stopword stripping they are too generic
    # ("felt like", "could feel") and over-flag human prose.
    gap = r"(?:\w+[''\w]*\s+){0,2}"
    tokens = sorted(gap.join(re.escape(w) for w in t[0].split())
                    for t in json.loads(fetch(SLOP_TRIGRAMS_URL)))
    write_rule("SlopTrigrams", {
        "extends": "existence",
        "message": "Matches slop-forensics overused trigram: '%s'.",
        "level": "suggestion",
        "ignorecase": True,
        "tokens": tokens,
    }, SLOP_TRIGRAMS_URL, "MIT (sam-paech/slop-forensics)")


def parse_nous_tables(md: str) -> dict[str, list[tuple[str, str]]]:
    tiers, current = {}, None
    for line in md.splitlines():
        if line.startswith("#"):  # any heading ends the current tier's table
            m = re.match(r"### (Tier \d)", line)
            current = m.group(1) if m else None
            if current:
                tiers[current] = []
            continue
        if current and line.startswith("|") and not re.match(r"^\|[\s\-|]+\|$", line):
            cells = [c.strip() for c in line.strip("|").split("|")]
            if len(cells) >= 2 and cells[0] and not cells[0].lower().startswith(("slop word", "phrase")):
                tiers[current].append((cells[0], cells[1]))
    return tiers


def nous_word(cell: str) -> list[str]:
    cell = re.sub(r"\([^)]*\)", "", cell).strip()  # drop "(verb)" qualifiers
    return [w.strip() for w in cell.split("/") if w.strip()]


def nous_phrase_regex(cell: str) -> str | None:
    p = cell.strip().strip('"').strip()
    p = re.sub(r"[.…]+$", "", p).rstrip(", ").strip()
    if p.lower() == "not just x, but y":  # template, covered by Deslop scaffold rule
        return None
    # "[fast-paced/digital/modern]" -> alternation
    def alt(m):
        return "(?:" + "|".join(re.escape(x) for x in m.group(1).split("/")) + ")"
    p = re.sub(r"\[([^\]]+)\]", alt, re.escape(p).replace(r"\[", "[").replace(r"\]", "]"))
    return p


def nous_rules():
    tiers = parse_nous_tables(fetch(NOUS_URL))
    note = "NONE (NousResearch/autonovel) — ⚠ license debt, excise before distribution"

    for tier, name, level in [("Tier 1", "NousTier1", "warning"), ("Tier 2", "NousTier2", "suggestion")]:
        swap, tokens = {}, []
        for word_cell, alt_cell in tiers[tier]:
            # "(as in 'a testament to')" rows target a construction, not the
            # word — a token swap would change part of speech; flag only
            construction = "(as in" in word_cell
            for w in nous_word(word_cell):
                if alt_cell.startswith("(") or construction:
                    tokens.append(w)
                else:
                    swap[w] = alt_cell.split(",")[0].strip()
        rule = {
            "extends": "substitution",
            "message": "Slop word (Nous %s): consider '%%s' instead of '%%s'." % tier.lower(),
            "level": level,
            "ignorecase": True,
            "swap": swap,
        }
        if tier == "Tier 1":  # tier 2 is context-dependent ("most robust" != "most strong")
            rule["action"] = {"name": "replace"}
        write_rule(name, rule, NOUS_URL, note)
        if tokens:
            write_rule(name + "NoSwap", {
                "extends": "existence",
                "message": "'%s' is a slop word with no clean substitute (Nous " + tier.lower() + ") — rewrite the sentence.",
                "level": level,
                "ignorecase": True,
                "tokens": sorted(tokens),
            }, NOUS_URL, note)

    tokens = [t for cell, _ in tiers["Tier 3"] if (t := nous_phrase_regex(cell))]
    write_rule("NousTier3Filler", {
        "extends": "existence",
        "message": "Filler phrase that adds no information (Nous tier 3) — delete or state the thing directly.",
        "level": "warning",
        "ignorecase": True,
        "tokens": sorted(tokens),
    }, NOUS_URL, note)


def main():
    import argparse
    ap = argparse.ArgumentParser(description="Generate the Deaiify Vale style.")
    ap.add_argument("--include-nous", action="store_true",
                    help="also generate Nous*.yml from NousResearch/autonovel ANTI-SLOP.md. "
                         "Upstream has NO license (all-rights-reserved); these files are "
                         "gitignored and must not be redistributed — local private use only.")
    args = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    print(f"generating {OUT}")
    kobak_rules()
    slop_forensics_rules()
    if args.include_nous:
        print("  (--include-nous: writing gitignored, unlicensed Nous*.yml — do not redistribute)")
        nous_rules()
    else:
        for f in OUT.glob("Nous*.yml"):  # keep the tree consistent with the default build
            f.unlink()
        print("  Nous rules skipped (opt in with --include-nous; see README §License)")


if __name__ == "__main__":
    main()
